# Configuration de la base de donnees PostgreSQL local access

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.sql.init.mode=always
spring.jpa.database=postgresql
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

########################################
# CORS
########################################

app.cors.allowed-origins=https://www.smart-invite.com

###################################
# REDIS
###################################

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=${REDISPASSWORD}
spring.data.redis.timeout=5000

########################################
# WhatsApp Process
########################################

# Environnement de travail
app.whatsapp.environnement=${NODE_ENV}

# En prod, le service WhatsApp est un service Railway séparé
app.whatsapp.auto-start=false
app.whatsapp.service-dir=./whatsapp-service

